version: "3.9"
services:
  app:
    build: .
    container_name: python_cmd
    tty: true
    stdin_open: true
    restart: on-failure

    volumes:
      - type: bind
        source: ./src
        target: /apps/src